# Generated by Django 5.2.1 on 2025-05-15 14:22

import detailsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperiencedApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('ssc_memo', models.FileField(upload_to=detailsapp.models.upload_path)),
                ('inter_memo', models.FileField(upload_to=detailsapp.models.upload_path)),
                ('degree_memo', models.FileField(upload_to=detailsapp.models.upload_path)),
                ('aadhar_card', models.FileField(upload_to=detailsapp.models.upload_path)),
                ('pan_card', models.FileField(upload_to=detailsapp.models.upload_path)),
                ('passport_photo', models.FileField(upload_to=detailsapp.models.upload_path)),
                ('pre_offer_letter', models.FileField(upload_to=detailsapp.models.upload_path)),
                ('pay_slips', models.FileField(upload_to=detailsapp.models.upload_path)),
                ('relevant_experience', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FresherApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('ssc_memo', models.FileField(upload_to=detailsapp.models.upload_path)),
                ('inter_memo', models.FileField(upload_to=detailsapp.models.upload_path)),
                ('degree_memo', models.FileField(upload_to=detailsapp.models.upload_path)),
                ('aadhar_card', models.FileField(upload_to=detailsapp.models.upload_path)),
                ('pan_card', models.FileField(upload_to=detailsapp.models.upload_path)),
                ('passport_photo', models.FileField(upload_to=detailsapp.models.upload_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
