# Generated by Django 5.2.1 on 2025-05-15 16:14

import detailsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencedapplicant',
            name='relevant_experience',
        ),
        migrations.AddField(
            model_name='experiencedapplicant',
            name='relieving_experience',
            field=models.FileField(blank=True, null=True, upload_to=detailsapp.models.upload_path),
        ),
    ]
