# Generated by Django 5.2.1 on 2025-05-15 16:26

import detailsapp.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailsapp', '0002_remove_experiencedapplicant_relevant_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencedapplicant',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fresherapplicant',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiencedapplicant',
            name='pay_slips',
            field=models.FileField(blank=True, null=True, upload_to=detailsapp.models.upload_path),
        ),
        migrations.AlterField(
            model_name='experiencedapplicant',
            name='pre_offer_letter',
            field=models.FileField(blank=True, null=True, upload_to=detailsapp.models.upload_path),
        ),
    ]
